### ISSUE TITLE
Verify that we are not affected by JWT 'alg' spoofing issues 

### ISSUE THREAD

**Issue by manuel-freire** [RotaruDan/test-users#32]
See https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/ for details

**Comment by RotaruDan** [comment]
The middleware we're using to sign and verify the tokens is the leatest version (as we can see it here https://github.com/RotaruDan/test-users/blob/master/package.json#L18) of `express-jwt` (https://github.com/auth0/express-jwt) maintained by the same guys (auth0).

`express-jwt` uses underneeth a version of `jsonwebtoken` (https://github.com/auth0/node-jsonwebtoken) compatible with the version 5.0.0, as it can be seen here https://github.com/auth0/express-jwt/blob/master/package.json#L39.

Furthermore, to generate (when the user Logs In, https://github.com/RotaruDan/test-users/blob/master/routes/login.js#L40) a token we also use the leatest version of `jsonwebtoken`, as it can be seen here https://github.com/RotaruDan/test-users/blob/master/package.json#L20 . Though this is probably irrelevant since the problem comes when we verify the token passed by the user, which is done by `express-jwt` middleware.

To wrap things up, everything gets delegated to a version 5.0.0 or more of `jsonwebtoken` module.
In its changelog we can see:
- v 4.2.2 verifies the `alg` field even if the `jws` dependency doesn't. 
- v 5.0.0 - updates to the latest version of `jws` which also checks the alg field (https://github.com/auth0/node-jsonwebtoken/blob/master/CHANGELOG.md#security)
